[package]
name = "rustson"
version = "0.2.11"
authors = ["Alexandre Maurel <alexandre.maurel@gmail.com>"]

[dependencies]
bytes = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_derive="1.0"

futures = "0.1"
tokio = "0.1"


[dev-dependencies]
#serde_derive="1.0"