[package]
name = "rustson"
version = "0.2.8"
authors = ["Alexandre Maurel <alexandre.maurel@gmail.com>"]

[dependencies]
bytes = "*"
serde = { version = "1.0", features = ["derive"] }
serde_derive="*"
serde_json = "1.0"
futures = "0.1.26"
tokio = "*"
tokio-core= "*"
