[package]
name = "rustson"
version = "0.2.3"
authors = ["Alexandre Maurel <alexandre.maurel@gmail.com>"]

[dependencies]
bytes = "*"
serde = { version = "1.0", features = ["derive"] }
serde_derive="*"
serde_json = "1.0"
