[package]
name = "rustson"
version = "0.4.2"
authors = ["Alexandre Maurel <alexandre.maurel@gmail.com>"]

[dependencies]
byteorder = "1.4"
bytes = "1.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_derive="1.0"
